# Generated by Django 3.2.3 on 2021-05-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bride',
            name='Location_District',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bride',
            name='Location_State',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bride',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
