# Generated by Django 3.2.3 on 2021-05-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_pages', '0002_auto_20210528_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='bride',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bride',
            name='Nakshatra',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bride',
            name='Phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bride',
            name='Post_Graduation_college',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='bride',
            name='Rasi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bride',
            name='Under_Graduation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bride',
            name='Under_Graduation_college',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='bride',
            name='profession',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bride',
            name='salary',
            field=models.BigIntegerField(null=True),
        ),
    ]
