# Generated by Django 3.2.3 on 2021-05-28 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_pages', '0003_auto_20210528_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bride',
            old_name='Location_District',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='bride',
            old_name='Location_State',
            new_name='State',
        ),
    ]
