# Generated by Django 3.2.3 on 2021-06-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_pages', '0005_auto_20210528_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='bride',
            name='Creator',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
