# Generated by Django 3.2.3 on 2021-06-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_pages', '0006_bride_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bride',
            name='Creator',
        ),
    ]
