# Generated by Django 3.2.3 on 2021-06-01 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrimony_pages', '0007_remove_bride_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bride',
            name='Creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
