# Generated by Django 3.2.3 on 2021-06-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_pages', '0008_bride_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bride',
            name='Jsonfield',
            field=models.JSONField(null=True),
        ),
    ]
