# Generated by Django 3.2.3 on 2021-06-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_pages', '0010_remove_bride_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='bride',
            name='Image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
