# Generated by Django 3.2.3 on 2021-06-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_pages', '0011_bride_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bride',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
